name = "vectech-line-customer-api"
main = "worker.js"
compatibility_date = "2026-09-21"

[[d1_databases]]
binding = "DB"
database_name = "vectech-line-customer-db"
database_id = "59f6183e-a182-42f3-a49d-704b1df09dd0"
